### ISSUE TITLE
Does this code with the HT1632 chips

### ISSUE THREAD

**Issue by richardhawthorn** [gauravmm/HT1632-for-Arduino#21]
Hi there, great library!

I've tried running your code with the Sure 3208 and it works nicely, this board uses the HT1632C chip.

I've also got a few Sure 0832 boards which don't seem to work.  These use the HT1632. Your code mentions working with the HT1632 in places, but doesn't seem to work out of the box.

Is this possible?

**Comment by fwpedrosa** [comment]
I'm having the same problem with HT1632 ( without C) richardhawthorn . My display works fine with  https://github.com/devdsp/HT1632-AVR this library, but it´s hard to edit. In this library the clock pin is used and works very well. U must to insert a delay to read the words.

**Comment by richardhawthorn** [comment]
I've used this one in the past, and it works, but the library from gauravmm is so simple, it would be great to use it for both displays.
