### ISSUE TITLE
drawTarget mising

### ISSUE THREAD

**Issue by biohazardxxx** [gauravmm/HT1632-for-Arduino#22]
Hi,

all text examples use the HT1632.drawTarget(BUFFER_BOARD(1)); but this does not exists.
Was it missed to be added?

Best regards
-Bio

**Comment by q2dg** [comment]
I think example codes should be updated as it's indicated here: https://github.com/gauravmm/HT1632-for-Arduino/blob/1a104dda2c7b5a375b9fbfad2bc621d5ee2a8a16/UPGRADE.md

**Comment by biohazardxxx** [comment]
I agree without this line it works fine.

**Comment by gauravmm** [comment]
Oops. That command is only necessary when multiple boards are attached. 

I'll clear it up in a future update.

Gaurav
