### ISSUE TITLE
font_end_generate instructions

### ISSUE THREAD

**Issue by Ukhauk** [gauravmm/HT1632-for-Arduino#33]
Hi awesome library worked first time on my sure 32 X 16 bi colour display

Started driving on and Arduino + ethernet board but swapped over to Wemos Arduino board without issue.

Sorry noob question trying to create a larger 16 high font to display scrolling time.

changed the font height on font_conv.html page to 16 selected load not sure what font step is left @ 10

Pasted the contents below  prog_uchar FONT_NAME [] PROGMEM = {  into 

font_end_generate page and it returns this ? thought this might be asci but doesn't convert to text

int FONT_NAME_END [] = {
	   1,   4,   7,  12,  17,  22,  26,  27,
	  30,  33,  36,  41,  43,  46,  47,  51,
	  55,  58,  62,  66,  70,  74,  78,  82,
	  86,  90,  91,  93,  97, 101, 105, 109,
	 114, 118, 122, 126, 130, 134, 138, 142,
	 146, 149, 153, 157, 161, 166, 171, 175,
	 179, 184, 188, 192, 195, 199, 203, 208,
	 213, 218, 222, 224, 228, 230, 233, 237,
	 237

Any help or directions appreciated

**Comment by gauravmm** [comment]
It's not ASCII. 

`FONT_NAME_END[i]` stores the number of the first byte _after_ the end of the `i`th character in the font, which is the `(32 + i)` ASCII character. This means that the data for character `i` is stored starting at index `FONT_NAME_END[i-1]` and ending at `FONT_NAME_END[i]`.

The font glyphs are stored in the `FONT_NAME` array, with each row corresponding to a glyph. Use the tools [here](https://github.com/gauravmm/HT1632-for-Arduino/tree/master/Utilities) to design glyphs and build the font array.

**Comment by Ukhauk** [comment]
Hi thanks for your reply I have tried to use the tools example font_conv.html if I change the Height to 16 for example and press the Load button its at that point I'm not sure what to do, I thought you might paste it into font_end_generate.html to get the new font name. Perhaps we could have something in the read me much appreciated

**Comment by Ukhauk** [comment]
I have found a font_7x6.h for your library on the web perhaps some more font sizes for larger displays could be uploaded to your github Library

**Comment by gauravmm** [comment]
Sure, if you submit a pull request with a large font, I'll be happy to merge it.
