### ISSUE TITLE
24x16 Bicolor support

### ISSUE THREAD

**Issue by Dancopy** [gauravmm/HT1632-for-Arduino#39]
Greetings gauravmm
In your library, in file HT1632.h, there is no related module "24x16 Bicolor", which are marketed nowadays (at least on ebay), although you say that this can be changed in the line "//Size of COM and OUT in bits:" but I saw reports that it did not work, so would not it be correct to add a line like this to the file?

// SureElectronics 24x16 Bicolor LED Dot Matrix Unit Board
#define TYPE_2416_BICOLOR 1

Also, did you update your library, given some bug that caused multiple displays?

Thank you and congratulations for the hard but, excellent work,

Daniel Fernandes

**Comment by gauravmm** [comment]
Hi Daniel,

Thanks for the tip! I had no idea that there was a new type of display out. If you have such a display, I'd really appreciate help in getting it to work with the library. I will accept your pull request if you have one.

Thanks,
Gaurav
