### ISSUE TITLE
Inverted/Flipped Text Using HT1632.drawText() function 

### ISSUE THREAD

**Issue by anagen** [gauravmm/HT1632-for-Arduino#41]
Hello,

While Draw Image function works well but drawText() function is printing Inverted/flipped text
on the display.

I am using 24x16 single Module.

Any help ?

**Comment by anagen** [comment]
Update  :  Apparently both Images & Text appears flipped  on the Display.

**Comment by Omidttl** [comment]
in my case, it works fine, try to check ur wirings
