### ISSUE TITLE
Library won't work with Sure Electronics 2416 Red from 2010

### ISSUE THREAD

**Issue by nosemangr** [gauravmm/HT1632-for-Arduino#42]
Hi,
recently I unearthed two Sure Electronics 2416 Red from 2010 and tested them with Bill Westfield's code (circa 2008 - "Random Walk" and other examples) and they both worked without a problem.
Unfortunately, they won't work with neither your library, nor the Adafruit HT1632 library. None of the examples work, nor any of the Adafruit ones. Tried with Arduino UNO, and an R3 Elegoo to make sure.

Has something changed since the 2008 code was written that would make them incompatible with your library?
What other information could I provide to find what the problem is?

As far as I know, I did the proper selection in the HT1632.h file and commented out the other boards. I used this one:
```
// SureElectronics 24x16 Monochrome LED Dot Matrix Unit Board
#define TYPE_2416_MONO 1
```

Thank you in advance.
Athanasios

**Comment by nosemangr** [comment]
a bit more context in case it matters:
The Chip is the old HT1632 and not the "C" variant.
The board has a code of: DE-DP016 VER1.1

Cheers

**Comment by gauravmm** [comment]
Oh man I haven't worked on this in ages. Going by [this](https://github.com/gauravmm/HT1632-for-Arduino/blob/master/HT1632.cpp#L152-L156) comment, you could try changing the initialization code to send the `RC_MASTER_MODE` command.

I remember the original datasheet had the entire initialization procedure laid out. You could compare that with what the `initialize` function does.

**Comment by nosemangr** [comment]
> Oh man I haven't worked on this in ages. Going by [this](https://github.com/gauravmm/HT1632-for-Arduino/blob/master/HT1632.cpp#L152-L156) comment, you could try changing the initialization code to send the `RC_MASTER_MODE` command.
> 
> I remember the original datasheet had the entire initialization procedure laid out. You could compare that with what the `initialize` function does.

Thank you very much for the reply. I'll try your suggestion and post any findings here for others to access.
Also, thank you for making this library in the first place!
Cheers

**Comment by nosemangr** [comment]
I replaced the init code, and now I get some indications of life, but the examples and a test Sketch I wrote gives me wonky results.
The Heart example, only blinks on the Top right tile, and skips lines.
The sketch I wrote loops x (0-23) and y (0-15) using the HT1632.setPixel(  x , y ) and only lights LEDs up on the top 3 tiles and in a rather odd fashion.
I know this is not enough to get a definitive answer, so all I can ask for is "what am I looking for in the code"? I'm not a developer, and my coding skills are "spaghetti" grade (I can read code and copy paste).
I could post a video of what I get, and my code, but I don't want to waste your time :-)
Thanks

**Comment by nosemangr** [comment]
Solved. For anyone interested, you need to edit the "HT1632.cpp" under the aforementioned comment, and add:
writeCommand(HT1632_CMD_MSTMD);

change the:
writeCommand(HT1632_CMD_COMS01) to writeCommand(HT1632_CMD_COMS11);
(01 to 11).
This solution is for the board I mentioned in the OT, and make sure you edit the "HT1632.h" file appropriately after reading the comments.
Thank you Gaurav very much for providing the lead.
![code changes](https://user-images.githubusercontent.com/79033102/108932553-8c978e00-7617-11eb-963d-3b0628d9a3b6.png)

**Comment by gauravmm** [comment]
Awesome! I'm glad it worked.
