### ISSUE TITLE
the given library shows the letters inverted!! any help ??!!

### ISSUE THREAD

**Issue by R-A** [gauravmm/HT1632-for-Arduino#9]
Hi there
do any one please help me in this issue, i've tried gauravmm's library and it's sketch_HT1632_sample_code to my 26*24 led matrix display..
but  it shows the text as MIRROR inverted . "HELLO HOW ARE YOU? " is inverted !!!

my led matrix is a sure-electronics like display , as i built it to be like that of 24*16 sure electronics.
any clue about how to fix this problem??
please any answer is appreciated....i do need help.

Thanks in advance

**Comment by goerlitzer** [comment]
@gauravmm 
I got the same problem.

Your old link does not work anymore.

> "There's no easy fix to this, but the quickest fix that I can think of is to
> modify the library to write to display in reverse. This is the function
> that does the writing:
> https://github.com/gauravmm/HT1632-for-Arduino/blob/master/Arduino/HT1632/HT1632.cpp#L199-265"

Can you help me please?

Thank you

Regards,
Lars

**Comment by gauravmm** [comment]
The last action on this issue was seven years ago. Kudos for finding it.

You have to modify the function HT1632Class::render, there are two versions selected between based on the display type macro. (see [this](https://github.com/gauravmm/HT1632-for-Arduino/blob/e68bef04d8ce4ca8c9b45cc8b5ebb0c8a3fbe786/HT1632.cpp#L386) or [this](https://github.com/gauravmm/HT1632-for-Arduino/blob/e68bef04d8ce4ca8c9b45cc8b5ebb0c8a3fbe786/HT1632.cpp#L409))

**Comment by goerlitzer** [comment]
@gauravmm 
Thank you very much for your quick answer, I will test it.

And I can't compile your library with an ESP8266. The error message is
`exit status 1`
and quite a lot of funny lines, I can copy it to you if it helps you. It works great with an Arduino Nano. Do you have any idea why? The problem could be in the ht1632.h file

**Comment by gauravmm** [comment]
I'm afraid I don't have the time to support another platform; if you can figure out what the problem is, feel free to submit a pull request.

**Comment by anagen** [comment]
Simple fix for making is work for ESP8266 is 
  1. go to .cpp file 
  2. go to "min" function
  3  change to "_min"
  4. Save & Compile your Sketch, it should work

**Comment by anagen** [comment]
> @gauravmm
> Thank you very much for your quick answer, I will test it.
> 
> And I can't compile your library with an ESP8266. The error message is
> `exit status 1`
> and quite a lot of funny lines, I can copy it to you if it helps you. It works great with an Arduino Nano. Do you have any idea why? The problem could be in the ht1632.h file

Simple fix for making is work for ESP8266 is 
  1. go to .cpp file 
  2. go to "min" function
  3  change to "_min"
  4. Save & Compile your Sketch, it should work
